src/CarsInventory.Web/Models/CarViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace CarsInventory.Web.Models
{
    public class CarViewModel
    {
        public int Id { get; set; }

        [Required]
        public string Brand { get; set; }

        [Required]
        public string Model { get; set; }

        [Required]
        public int Year { get; set; }

        [Required]
        public decimal Price { get; set; }

        public bool? New { get; set; }
    }
}

src/CarsInventory.Web/Controllers/Ajax/CarsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CarsInventory.Core.Entities;
using CarsInventory.Infrastructure;
using CarsInventory.Web.Models;

namespace CarsInventory.Web.Controllers.Ajax
{
    [Authorize]
    public class CarsController : Controller
    {
        [HttpGet]
        [Route("Cars/GetCar/{carId:int}")]
        public ActionResult GetCar(int carId)
        {
            using (var unitOfWork = new UnitOfWork())
            {
                var existingCar = unitOfWork.CarRepository.Get(carId);

                if (existingCar == null)
                    return HttpNotFound("Invalid car");

                return Json(existingCar, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        [Route("Cars/SaveCar")]
        public ActionResult SaveCar(string brand, string model, decimal price, int year, bool? isNew = false)
        {
            using (var unitOfWork = new UnitOfWork())
            {
                var currentUser = HttpContext.User.Identity.Name;
                var newCar = new Car()
                {
                    
                    Brand = brand,
                    Model = model,
                    Price = price,
                    Year = year,
                    New = isNew.HasValue && isNew.Value,
                    Owner = currentUser
                };

                unitOfWork.CarRepository.Insert(newCar);
                unitOfWork.SaveChanges();
                return Content(string.Empty);

            }
        }

        [HttpPost]
        [Route("Cars/SaveCar/{carId:int}")]
        public ActionResult SaveCar(int id, string brand, string model, decimal price, int year, bool? isNew = false)
        {
            using (var unitOfWork = new UnitOfWork())
            {
                var existingCar = unitOfWork.CarRepository.Get(id);

                if (existingCar == null)
                    return HttpNotFound("Invalid car");

                var currentUser = HttpContext.User.Identity.Name;
                if (existingCar.Owner != currentUser)
                {
                    Response.StatusCode = 400;
                    return Content("You don't have permission to update this car");
                }

                existingCar.Brand = brand;
                existingCar.Model = model;
                existingCar.Price = price;
                existingCar.Year = year;
                existingCar.New = isNew.HasValue && isNew.Value;

                unitOfWork.CarRepository.Update(existingCar);
                unitOfWork.SaveChanges();
                return Content(string.Empty);

            }
        }

    }
}

src/CarsInventory.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CarsInventory.Infrastructure;
using CarsInventory.Web.Models;

namespace CarsInventory.Web.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult CarList(string search = null)
        {
            using (var unitOfWork = new UnitOfWork())
            {
                var currentUser = User.Identity.Name;

                var cars = unitOfWork.CarRepository.GetList(currentUser, search);
                return PartialView("CarList", cars.Select(x => new CarViewModel()
                {
                    Id = x.Id,
                    Brand = x.Brand,
                    Model = x.Model,
                    Year = x.Year,
                    Price = x.Price,
                    New = x.New
                }).ToList());
            }
        }
    }
}

src/CarsInventory.Web/Views/Home/CarList.cshtml
@model IEnumerable<CarsInventory.Web.Models.CarViewModel>

<div>
    <table class="table table-sm">
        <thead class="thead-light">
            <tr>
                <th></th>
                <th scope="col">#</th>
                <th scope="col">Brand</th>
                <th scope="col">Model</th>
                <th scope="col">Year</th>
                <th scope="col">Price</th>
                <th scope="col">Is New</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var car in Model)
            {
                <tr>
                    <td><button class="btn btn-link" onclick="window.CarsInventory.showAddOrEditCar(@car.Id)">Edit</button></td>
                    <td scope="row">@car.Id</td>
                    <td scope="row">@car.Brand</td>
                    <td scope="row">@car.Model</td>
                    <td scope="row">@car.Year</td>
                    <td scope="row">@string.Format("{0:C}", car.Price)</td>
                    <td scope="row">@(car.New.HasValue && car.New.Value ? "Yes" : "No")</td>
                </tr>
            }
            @if (!Model.Any())
            {
                <tr><td colspan="7">No cars found</td></tr>
            }
        </tbody>
    </table>
</div>

src/CarsInventory.Web/Views/Home/Cars.cshtml
<div id="carListContainer" class="">
    @Html.Partial("CarList")
</div>

src/CarsInventory.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page - Ventive Cars Inventory";
}

<div class="mt-3">
    <div class="py-2 clearfix">
        <button class="btn btn-secondary" onclick="window.CarsInventory.showAddOrEditCar()">Add car</button>

        <div class="float-right">
            <form onsubmit="window.CarsInventory.searchCars(event)">
                <div class="input-group mb-3" style="width: 350px">
                    <input type="text" class="form-control" id="textSearch" placeholder="Search by brand or model">
                    <div class="input-group-append">
                        <button class="btn btn-outline-secondary" type="submit">Search</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <div id="carList">
        @Html.Action("CarList")
    </div>
</div>

<div class="modal fade" id="modalAddOrEditCar" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            @using (Html.BeginForm("SaveCar", "Cars", FormMethod.Post, new { id = "formAddOrEditCar", autocomplete = "off", @class = "form", onsubmit = "window.CarsInventory.saveCar(event)" }))
            {
                <div class="modal-header">
                    <h5 class="modal-title">Modal title</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <input type="hidden" name="Id" id="hiddenId" value="0" />
                    <div class="form-group">
                        <label for="textBrand">Brand</label>
                        <input type="text" class="form-control" name="Brand" id="textBrand" placeholder="Brand" required>
                    </div>
                    <div class="form-group">
                        <label for="textModel">Model</label>
                        <input type="text" class="form-control" name="Model" id="textModel" placeholder="Model" required>
                    </div>
                    <div class="form-group">
                        <label for="textModel">Year</label>
                        <input type="number" class="form-control" name="Year" id="numberYear" placeholder="Year" required>
                    </div>
                    <div class="form-group">
                        <label for="textModel">Price</label>
                        <input type="number" class="form-control" name="Price" id="numberPrice" placeholder="Price" required>
                    </div>
                    <div class="form-check">
                        <input type="checkbox" name="IsNew" value="true" checked="checked" class="form-check-input" id="checkNew">
                        <label class="form-check-label" for="checkNew">New?</label>
                    </div>

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Save</button>
                </div>
            }
        </div>
    </div>
</div>

@section scripts {
    <script src="../../Scripts/main.js"></script>
}